[package]
name = "server-rust-udp"
version = "0.1.0"
edition = "2018"

[dependencies]
bytes = "1.1"
tokio = { version = "1.0", features = ["full"] }
tokio-tungstenite = "0.14"
dashmap = "5.1"

[[bin]]
name = "server-rust-udp"
path = "src/main.rs"
