[package]
name = "client-rust"
version = "0.1.0"
edition = "2018"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.15"
futures-util = "0.3"
dashmap = "5.3"

[[bin]]
name = "client-rust"
path = "src/main.rs"
