[package]
name = "server-rust-tcp"
version = "0.1.0"
edition = "2018"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
tokio-tungstenite = "0.14"
futures-util = "0.3"
dashmap = "5.3"

[[bin]]
name = "server-rust-tcp"
path = "src/main.rs"
